# For more info on HTTP files go to https://aka.ms/vs/httpfile


@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWF4IiwiZXhwIjoxNjk4NDEwMTYwfQ.H2OMhyUZ_BoKgc09SniKWrRacwVeA_jVK71OaIu_3p1swIz_D3zwMdlcxLo-qTAV6TqcJbHC1HBrp9dY8OQbJg
@hostname=localhost
@port=7233
##

GET https://{{hostname}}:{{port}}/users
Authorization: Bearer {{token}}

{

}

